### ISSUE TITLE
JavaScript SDK integration doesn't work as documented with SvelteKit

### ISSUE THREAD

**Issue by 123remodeling** [upload-js/upload-js#8]
**Environment:** SvelteKit + Vercel

### Method 1
This one is from `upload-js` documentation. Works in `development`, doesn't work in `production`

```js
import { Upload } from "upload-js";

const upload = Upload({ apiKey: * });
```

**Error:**
```log
file:///var/task/.svelte-kit/output/server/entries/pages/_page.svelte.js:5
import { Upload } from "upload-js";
         ^^^^^^
SyntaxError: Named export 'Upload' not found. The requested module 'upload-js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'upload-js';
const { Upload } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

### Method 2
Works in `development`, doesn't work in `production`

```js
import * as UploadJS from 'upload-js';
const { Upload } = UploadJS;

const upload = Upload({ apiKey: * });
```

**Error:**
```log
TypeError: Upload is not a function
    at file:///var/task/.svelte-kit/output/server/entries/pages/_page.svelte.js:132:3
    at Object.$$render (file:///var/task/.svelte-kit/output/server/chunks/index2.js:187:18)
    at Object.default (file:///var/task/.svelte-kit/output/server/chunks/internal.js:69:98)
    at file:///var/task/.svelte-kit/output/server/entries/pages/_layout.svelte.js:18:33
    at Object.$$render (file:///var/task/.svelte-kit/output/server/chunks/index2.js:187:18)
    at file:///var/task/.svelte-kit/output/server/chunks/internal.js:58:101
    at $$render (file:///var/task/.svelte-kit/output/server/chunks/index2.js:187:18)
    at Object.render (file:///var/task/.svelte-kit/output/server/chunks/index2.js:195:20)
    at render_response (file:///var/task/.svelte-kit/output/server/index.js:1739:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Method 3
Works in both `production` and `development`. 

```js
import UploadJS from 'upload-js';
const { Upload } = UploadJS;

const upload = Upload({ apiKey: * });
```

**Comment by ljwagerfield** [comment]
Thank you for raising!

Glad there's a workaround for the short term.

We need to provide proper ES distributions for Upload.js, just like we are for the [Upload JavaScript SDK (Full Version)](https://github.com/upload-io/upload-javascript-sdk/blob/main/package.json#L8-L23).

Leaving this open until we address it 👍

**Comment by ljwagerfield** [comment]
Closing as the new Bytescale JavaScript SDK (which is a rewrite of Upload.js) supports browser ESM:

https://github.com/bytescale/bytescale-javascript-sdk/blob/cb1106de2d4b66a08fad508f22f8b264e9215e37/package.json#L8-L26
